create table public.todo (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  constraint todo_pkey primary key (id)
) TABLESPACE pg_default;