apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      restartPolicy: Always
      initContainers:
        - name: wait-for-db-and-analytics
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z {{ .Values.envMap.POSTGRES_HOST.value }} {{ .Values.envMap.POSTGRES_PORT.value }}; do echo waiting for db; sleep 2; done;
              until nc -z analytics 4000; do echo waiting for analytics; sleep 2; done;
      containers:
        - env:
            - name: API_EXTERNAL_URL
              value: "https://{{ .Values.hosts.app }}"
            - name: GOTRUE_API_HOST
              value: '0.0.0.0'
            - name: GOTRUE_API_PORT
              value: '9999'
            - name: GOTRUE_DB_DATABASE_URL
              value: "postgresql://supabase_auth_admin:{{ .Values.envMap.POSTGRES_PASSWORD.value }}@{{ .Values.envMap.POSTGRES_HOST.value }}:{{ .Values.envMap.POSTGRES_PORT.value }}/{{ .Values.envMap.POSTGRES_DB.value }}"
            - name: GOTRUE_DB_DRIVER
              value: postgres
            - name: GOTRUE_DISABLE_SIGNUP
              value: {{ .Values.envMap.DISABLE_SIGNUP.value | quote }}
            - name: GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED
              value: {{ .Values.envMap.ENABLE_ANONYMOUS_USERS.value | quote }}
            - name: GOTRUE_EXTERNAL_EMAIL_ENABLED
              value: {{ .Values.envMap.ENABLE_EMAIL_SIGNUP.value | quote }}
            - name: GOTRUE_EXTERNAL_PHONE_ENABLED
              value: {{ .Values.envMap.ENABLE_PHONE_SIGNUP.value | quote }}
            - name: GOTRUE_JWT_ADMIN_ROLES
              value: service_role
            - name: GOTRUE_JWT_AUD
              value: authenticated
            - name: GOTRUE_JWT_DEFAULT_GROUP_NAME
              value: authenticated
            - name: GOTRUE_JWT_EXP
              value: {{ .Values.envMap.JWT_EXPIRY.value | quote }}
            - name: GOTRUE_JWT_SECRET
              value: {{ .Values.envMap.JWT_SECRET.value | quote }}
            - name: GOTRUE_MAILER_AUTOCONFIRM
              value: {{ .Values.envMap.ENABLE_EMAIL_AUTOCONFIRM.value | quote }}
            - name: GOTRUE_MAILER_URLPATHS_CONFIRMATION
              value: /auth/v1/verify
            - name: GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE
              value: /auth/v1/verify
            - name: GOTRUE_MAILER_URLPATHS_INVITE
              value: /auth/v1/verify
            - name: GOTRUE_MAILER_URLPATHS_RECOVERY
              value: /auth/v1/verify
            - name: GOTRUE_SITE_URL
              value: {{ .Values.envMap.SITE_URL.value | quote }}
            - name: GOTRUE_SMS_AUTOCONFIRM
              value: {{ .Values.envMap.ENABLE_PHONE_AUTOCONFIRM.value | quote }}
            - name: GOTRUE_SMTP_ADMIN_EMAIL
              value: {{ .Values.envMap.SMTP_ADMIN_EMAIL.value | quote }}
            - name: GOTRUE_SMTP_HOST
              value: {{ .Values.envMap.SMTP_HOST.value | quote }}
            - name: GOTRUE_SMTP_PASS
              value: {{ .Values.envMap.SMTP_PASS.value | quote }}
            - name: GOTRUE_SMTP_PORT
              value: {{ .Values.envMap.SMTP_PORT.value | quote }}
            - name: GOTRUE_SMTP_SENDER_NAME
              value: {{ .Values.envMap.SMTP_SENDER_NAME.value | quote }}
            - name: GOTRUE_SMTP_USER
              value: {{ .Values.envMap.SMTP_USER.value | quote }}
            - name: GOTRUE_URI_ALLOW_LIST
              value: {{ .Values.envMap.ADDITIONAL_REDIRECT_URLS.value | quote }}
          image: supabase/gotrue:v2.177.0
          # livenessProbe:
          #   exec:
          #     command:
          #       - wget
          #       - --no-verbose
          #       - --tries=1
          #       - --spider
          #       - http://localhost:9999/health
          #   failureThreshold: 3
          #   periodSeconds: 5
          #   timeoutSeconds: 5
          name: supabase-auth
          ports:
            - containerPort: 9999
