apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
spec:
  ports:
    - name: 'postgres'
      port: {{ .Values.envMap.POSTGRES_PORT.value }}
      targetPort: {{ .Values.envMap.POSTGRES_PORT.value }}
  selector:
    app: postgres
