apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      restartPolicy: Always

      # Allow /etc/postgresql-custom for the postgres user
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "mkdir -p /etc/postgresql-custom && chmod 0770 /etc/postgresql-custom && chown 105:105 /etc/postgresql-custom"]
        volumeMounts:
          - name: pgsodium-mount
            mountPath: /etc/postgresql-custom

      containers:
        - args:
            - postgres
            - -c
            - config_file=/etc/postgresql/postgresql.conf
            - -c
            - log_min_messages=fatal
          env:
            - name: JWT_EXP
              value: {{ .Values.envMap.JWT_EXPIRY.value | quote }}
            - name: JWT_SECRET
              value: {{ .Values.envMap.JWT_SECRET.value | quote }}
            - name: PGDATABASE
              value: {{ .Values.envMap.POSTGRES_DB.value | quote }}
            - name: PGPASSWORD
              value: {{ .Values.envMap.POSTGRES_PASSWORD.value | quote }}
            - name: PGPORT
              value: {{ .Values.envMap.POSTGRES_PORT.value | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.envMap.POSTGRES_DB.value | quote }}
            - name: POSTGRES_HOST
              value: /var/run/postgresql
            - name: POSTGRES_PASSWORD
              value: {{ .Values.envMap.POSTGRES_PASSWORD.value | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.envMap.POSTGRES_PORT.value | quote }}
          image: {{ .Values.images.db }}
          # livenessProbe:
          #   exec:
          #     command:
          #       - pg_isready
          #       - -U
          #       - postgres
          #       - -h
          #       - localhost
          #   failureThreshold: 10
          #   periodSeconds: 5
          #   timeoutSeconds: 5
          name: supabase-db
          ports:
            - containerPort: {{ .Values.envMap.POSTGRES_PORT.value }}
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/migrations/99-realtime.sql
              subPath: realtime.sql
              name: db-config
              readOnly: true
            - mountPath: /docker-entrypoint-initdb.d/init-scripts/98-webhooks.sql
              subPath: webhooks.sql
              name: db-config
              readOnly: true
            - mountPath: /docker-entrypoint-initdb.d/init-scripts/99-roles.sql
              subPath: roles.sql
              name: db-config
              readOnly: true
            - mountPath: /docker-entrypoint-initdb.d/init-scripts/99-jwt.sql
              subPath: jwt.sql
              name: db-config
              readOnly: true
            - mountPath: /docker-entrypoint-initdb.d/migrations/97-_supabase.sql
              subPath: _supabase.sql
              name: db-config
              readOnly: true
            - mountPath: /docker-entrypoint-initdb.d/migrations/99-logs.sql
              subPath: logs.sql
              name: db-config
              readOnly: true
            - mountPath: /docker-entrypoint-initdb.d/migrations/99-pooler.sql
              subPath: pooler.sql
              name: db-config
              readOnly: true
            - mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
              name: db-config
              readOnly: true
            - mountPath: /etc/postgresql-custom
              name: pgsodium-mount
            - mountPath: /var/lib/postgresql/data
              name: postgres-mount
      volumes:
        - name: db-config
          hostPath:
            path: "{{ .Values.storage.code.hostPath }}/{{ .Values.identifier }}/volumes/db"
        - name: pgsodium-mount
          hostPath:
            path: {{ $.Values.storage.pgsodium.hostPath }}
        - name: postgres-mount
          hostPath:
            path: {{ $.Values.storage.postgres.hostPath }}
