apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: functions
  name: functions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: functions
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: functions
    spec:
      restartPolicy: Always
      initContainers:
        - name: wait-for-analytics
          image: busybox
          command:
            - sh
            - -c
            - until nc -z analytics 4000; do echo waiting for analytics; sleep 2; done;
      containers:
        - args:
            - start
            - --main-service
            - /home/deno/functions/main
          env:
            - name: JWT_SECRET
              value: {{ .Values.envMap.JWT_SECRET.value | quote }}
            - name: SUPABASE_ANON_KEY
              value: {{ .Values.envMap.ANON_KEY.value | quote }}
            - name: SUPABASE_DB_URL
              value: "postgresql://{{ .Values.envMap.POSTGRES_USER.value }}:{{ .Values.envMap.POSTGRES_PASSWORD.value }}@{{ .Values.envMap.POSTGRES_HOST.value }}:{{ .Values.envMap.POSTGRES_PORT.value }}/{{ .Values.envMap.POSTGRES_DB.value }}"
            - name: SUPABASE_SERVICE_ROLE_KEY
              value: {{ .Values.envMap.SERVICE_ROLE_KEY.value | quote }}
            - name: SUPABASE_URL
              value: {{ .Values.envMap.KONG_INTERNAL_URL.value | quote }}
            - name: VERIFY_JWT
              value: {{ .Values.envMap.FUNCTIONS_VERIFY_JWT.value | quote }}
          image: {{ .Values.images.functions }}
          name: supabase-functions
          ports:
            - containerPort: 9000
          volumeMounts:
            {{- if hasKey .Values.storage "code" }}
            - mountPath: /home/deno/functions
              name: functions-mount
            {{- end }}
      volumes:
        {{- if hasKey .Values.storage "code" }}
        - name: functions-mount
          hostPath:
            path: "{{ .Values.storage.code.hostPath }}/{{ .Values.identifier }}/functions"
        {{- end }}
