apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-prepuller-concurrent
  labels:
    app: image-prepuller
spec:
  selector:
    matchLabels:
      app: image-prepuller
  template:
    metadata:
      labels:
        app: image-prepuller
    spec:
      tolerations:
        - operator: Exists

      # IMPORTANT: normal containers pull concurrently
      containers:
        - name: pull-postgres
          image: supabase/postgres:15.8.1.060
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "echo 'postgres pulled'; sleep 3600"]
          resources:
            limits:
              cpu: 50m
              memory: 64Mi

        - name: pull-studio
          image: supabase/studio:2025.06.30-sha-6f5982d
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "echo 'studio pulled'; sleep 3600"]
          resources:
            limits:
              cpu: 50m
              memory: 64Mi

        - name: pull-realtime
          image: supabase/realtime:v2.34.47
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "echo 'realtime pulled'; sleep 3600"]
          resources:
            limits:
              cpu: 50m
              memory: 64Mi

        - name: pull-storage
          image: supabase/storage-api:v1.25.7
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "echo 'storage pulled'; sleep 3600"]
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
