apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    _format_version: '2.1'
    _transform: true

    ###
    ### Consumers / Users
    ###
    consumers:
      - username: DASHBOARD
      - username: anon
        keyauth_credentials:
          - key: $SUPABASE_ANON_KEY
      - username: service_role
        keyauth_credentials:
          - key: $SUPABASE_SERVICE_KEY
      - username: studio-anon
      - username: studio-admin
        jwt_secrets:
          - key: studio-admin
            secret: "replace-with-a-very-long-random-string"

    ###
    ### Access Control List
    ###
    acls:
      - consumer: anon
        group: anon
      - consumer: service_role
        group: admin

    ###
    ### Diploi login
    ###
    plugins:
      - name: request-termination
        consumer: studio-anon
        config:
          status_code: 401
          content_type: "text/html; charset=utf-8"
          body: |
            <!DOCTYPE html>
            <html>
              <head>
                <title>Supabase</title>
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <style>
                  * {
                    font-family: sans-serif;
                    font-size: 16px;
                  }
                  html,
                  body {
                    margin: 0;
                    min-height: 100vh;
                    background: #202328;
                    color: #fff;
                  }
                  body,
                  form {
                    display: flex;
                    flex-direction: column;
                    gap: 8px;
                  }
                  body {
                    padding: 32px;
                    align-items: center;
                    justify-content: center;
                    box-sizing: border-box;
                  }
                  p,
                  form,
                  hr {
                    max-width: min(400px, 100%);
                  }
                  p {
                    text-align: center;
                    opacity: 0.8;
                  }
                  form > p {
                    font-size: 12px;
                  }
                  input {
                    padding: 12px;
                    background: #31363f;
                    border-radius: 6px;
                    border: none;
                    color: #fff;
                  }
                  button,
                  .button {
                    padding: 10px 18px;
                    align-self: center;
                    text-decoration: none;
                    background: #6650fa;
                    border-radius: 64px;
                    border: none;
                    color: #fff;
                    cursor: pointer;
                  }
                  a {
                    font-size: inherit;
                    color: inherit;
                  }
                  hr {
                    display: block;
                    margin: 32px 0;
                    width: 100%;
                    height: 2px;
                    background: #31363f;
                    border: none;
                  }
                </style>
              </head>
              <body>
                <img
                  alt="supabase logo"
                  src="https://github.com/diploi/component-supabase/raw/main/.diploi/icon.svg"
                  width="64"
                  height="64"
                />
                <p>
                  <strong>You have been logged out.</strong><br />Login again from the
                  <a href="https://console.diploi.com/">Diploi Console</a>, or enter
                  credentials for the admin account below.
                </p>
                <a class="button" href="https://console.diploi.com/">Open Diploi Console</a>
                <hr />
                <form>
                  <input name="username" placeholder="Username" />
                  <input name="password" placeholder="Password" type="password" />
                  <p>
                    You can find the admin credentials from this deployments "Options" tab
                    in the <a href="https://console.diploi.com/">Diploi Console</a>.
                  </p>
                  <button>Login</button>
                </form>
              </body>
            </html>

    ###
    ### API Routes
    ###
    services:
      ## Open Auth routes
      - name: auth-v1-open
        url: $AUTH_INTERNAL_URL/verify
        routes:
          - name: auth-v1-open
            strip_path: true
            paths:
              - /auth/v1/verify
        plugins:
          - name: cors
      - name: auth-v1-open-callback
        url: $AUTH_INTERNAL_URL/callback
        routes:
          - name: auth-v1-open-callback
            strip_path: true
            paths:
              - /auth/v1/callback
        plugins:
          - name: cors
      - name: auth-v1-open-authorize
        url: $AUTH_INTERNAL_URL/authorize
        routes:
          - name: auth-v1-open-authorize
            strip_path: true
            paths:
              - /auth/v1/authorize
        plugins:
          - name: cors

      ## Secure Auth routes
      - name: auth-v1
        _comment: 'GoTrue: /auth/v1/* -> $AUTH_INTERNAL_URL/*'
        url: $AUTH_INTERNAL_URL/
        routes:
          - name: auth-v1-all
            strip_path: true
            paths:
              - /auth/v1/
        plugins:
          - name: cors
          - name: key-auth
            config:
              hide_credentials: false
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - admin
                - anon

      ## Secure REST routes
      - name: rest-v1
        _comment: 'PostgREST: /rest/v1/* -> $REST_INTERNAL_URL/*'
        url: $REST_INTERNAL_URL/
        routes:
          - name: rest-v1-all
            strip_path: true
            paths:
              - /rest/v1/
        plugins:
          - name: cors
          - name: key-auth
            config:
              hide_credentials: true
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - admin
                - anon

      ## Secure GraphQL routes
      - name: graphql-v1
        _comment: 'PostgREST: /graphql/v1/* -> $REST_INTERNAL_URL/rpc/graphql'
        url: $REST_INTERNAL_URL/rpc/graphql
        routes:
          - name: graphql-v1-all
            strip_path: true
            paths:
              - /graphql/v1
        plugins:
          - name: cors
          - name: key-auth
            config:
              hide_credentials: true
          - name: request-transformer
            config:
              add:
                headers:
                  - Content-Profile:graphql_public
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - admin
                - anon

      ## Secure Realtime routes
      - name: realtime-v1-ws
        _comment: 'Realtime: /realtime/v1/* -> $REALTIME_INTERNAL_URL/socket/*'
        url: http://realtime.$DIPLOI_NAMESPACE:4000/socket
        protocol: ws
        routes:
          - name: realtime-v1-ws
            strip_path: true
            paths:
              - /realtime/v1/
        plugins:
          - name: cors
          - name: key-auth
            config:
              hide_credentials: false
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - admin
                - anon
      - name: realtime-v1-rest
        _comment: 'Realtime: /realtime/v1/* -> $REALTIME_INTERNAL_URL/socket/*'
        url: http://realtime.$DIPLOI_NAMESPACE:4000/api
        protocol: http
        routes:
          - name: realtime-v1-rest
            strip_path: true
            paths:
              - /realtime/v1/api
        plugins:
          - name: cors
          - name: key-auth
            config:
              hide_credentials: false
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - admin
                - anon
      ## Storage routes: the storage server manages its own auth
      - name: storage-v1
        _comment: 'Storage: /storage/v1/* -> $STORAGE_INTERNAL_URL/*'
        url: $STORAGE_INTERNAL_URL/
        routes:
          - name: storage-v1-all
            strip_path: true
            paths:
              - /storage/v1/
        plugins:
          - name: cors

      ## Edge Functions routes
      - name: functions-v1
        _comment: 'Edge Functions: /functions/v1/* -> $FUNCTIONS_INTERNAL_URL/*'
        url: $FUNCTIONS_INTERNAL_URL/
        routes:
          - name: functions-v1-all
            strip_path: true
            paths:
              - /functions/v1/
        plugins:
          - name: cors

      ## Analytics routes
      - name: analytics-v1
        _comment: 'Analytics: /analytics/v1/* -> $ANALYTICS_INTERNAL_URL/*'
        url: $ANALYTICS_INTERNAL_URL/
        routes:
          - name: analytics-v1-all
            strip_path: true
            paths:
              - /analytics/v1/

      ## Secure Database routes
      - name: meta
        _comment: 'pg-meta: /pg/* -> $META_INTERNAL_URL/*'
        url: $META_INTERNAL_URL/
        routes:
          - name: meta-all
            strip_path: true
            paths:
              - /pg/
        plugins:
          - name: key-auth
            config:
              hide_credentials: false
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - admin

      ## Protected Dashboard - catch all remaining routes
      - name: dashboard
        _comment: 'Studio: /* -> $STUDIO_INTERNAL_URL/*'
        url: $STUDIO_INTERNAL_URL/
        routes:
          - name: dashboard-all
            strip_path: true
            paths:
              - /
        plugins:
          - name: cors
          - name: jwt
            config:
              cookie_names: ["sb-studio"]
              key_claim_name: "iss"
              claims_to_verify: ["exp"]
              anonymous: studio-anon
