apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kong
  name: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kong
    spec:
      restartPolicy: Always
      initContainers:
        - name: wait-for-analytics
          image: busybox
          command:
            - sh
            - -c
            - until nc -z analytics 4000; do echo waiting for analytics; sleep 2; done;
      containers:
        - env:
            - name: KONG_DATABASE
              value: 'off'
            - name: KONG_DECLARATIVE_CONFIG
              value: /home/kong/kong.yml
            - name: KONG_DNS_ORDER
              value: LAST,A,CNAME
            - name: KONG_NGINX_PROXY_PROXY_BUFFERS
              value: '64 160k'
            - name: KONG_NGINX_PROXY_PROXY_BUFFER_SIZE
              value: 160k
            - name: KONG_PLUGINS
              value: 'request-transformer,cors,key-auth,acl,basic-auth,request-termination,jwt'
          image: {{ .Values.images.kong }}
          name: supabase-kong
          ports:
            - containerPort: 8000
            - containerPort: 8443
          volumeMounts:
            - mountPath: /home/kong/kong.yml
              subPath: kong.yml
              name: kong-config
              readOnly: true
      volumes:
        - name: kong-config
          configMap:
            name: kong-config
