apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kong
  name: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kong
    spec:
      restartPolicy: Always
      containers:
        - command:
            - bash
            - -c
            - eval "echo \"$(cat ~/temp.yml)\"" > ~/kong.yml && /docker-entrypoint.sh kong docker-start
          env:
            - name: DASHBOARD_PASSWORD
              value: {{ .Values.envMap.DASHBOARD_PASSWORD.value | quote }}
            - name: DASHBOARD_USERNAME
              value: {{ .Values.envMap.DASHBOARD_USERNAME.value | quote }}
            - name: KONG_DATABASE
              value: 'off'
            - name: KONG_DECLARATIVE_CONFIG
              value: /home/kong/kong.yml
            - name: KONG_DNS_ORDER
              value: LAST,A,CNAME
            - name: KONG_NGINX_PROXY_PROXY_BUFFERS
              value: '64 160k'
            - name: KONG_NGINX_PROXY_PROXY_BUFFER_SIZE
              value: 160k
            - name: KONG_PLUGINS
              value: 'request-transformer,cors,key-auth,acl,basic-auth'
            - name: SUPABASE_ANON_KEY
              value: {{ .Values.envMap.ANON_KEY.value | quote }}
            - name: SUPABASE_SERVICE_KEY
              value: {{ .Values.envMap.SERVICE_ROLE_KEY.value | quote }}
            - name: DIPLOI_NAMESPACE
              value: {{ .Values.identifier | quote }}
            - name: AUTH_INTERNAL_URL
              value: {{ .Values.envMap.AUTH_INTERNAL_URL.value | quote }}
            - name: REST_INTERNAL_URL
              value: {{ .Values.envMap.REST_INTERNAL_URL.value | quote }}
            - name: REALTIME_INTERNAL_URL
              value: {{ .Values.envMap.REALTIME_INTERNAL_URL.value | quote }}
            - name: STORAGE_INTERNAL_URL
              value: {{ .Values.envMap.STORAGE_INTERNAL_URL.value | quote }}
            - name: FUNCTIONS_INTERNAL_URL
              value: {{ .Values.envMap.FUNCTIONS_INTERNAL_URL.value | quote }}
            - name: ANALYTICS_INTERNAL_URL
              value: {{ .Values.envMap.ANALYTICS_INTERNAL_URL.value | quote }}
            - name: META_INTERNAL_URL
              value: {{ .Values.envMap.META_INTERNAL_URL.value | quote }}
            - name: STUDIO_INTERNAL_URL
              value: {{ .Values.envMap.STUDIO_INTERNAL_URL.value | quote }}
          image: {{ .Values.images.kong }}
          name: supabase-kong
          ports:
            - containerPort: 8000
            - containerPort: 8443
          volumeMounts:
            - mountPath: /home/kong/temp.yml
              subPath: kong.yml
              name: kong-config
              readOnly: true
      volumes:
        - name: kong-config
          hostPath:
            path: "{{ .Values.storage.code.hostPath }}/{{ .Values.identifier }}/volumes/api/kong.yml"
            type: File
