apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rest
  name: rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      restartPolicy: Always
      containers:
        - args:
            - postgrest
          env:
            - name: PGRST_APP_SETTINGS_JWT_EXP
              value: {{ .Values.envMap.JWT_EXPIRY | quote }}
            - name: PGRST_APP_SETTINGS_JWT_SECRET
              value: {{ .Values.envMap.JWT_SECRET | quote }}
            - name: PGRST_DB_ANON_ROLE
              value: anon
            - name: PGRST_DB_SCHEMAS
              value: {{ .Values.envMap.PGRST_DB_SCHEMAS | quote }}
            - name: PGRST_DB_URI
              value: "postgres://authenticator:{{ .Values.envMap.POSTGRES_PASSWORD }}@{{ .Values.envMap.POSTGRES_HOST }}:{{ .Values.envMap.POSTGRES_PORT }}/{{ .Values.envMap.POSTGRES_DB }}"
            - name: PGRST_DB_USE_LEGACY_GUCS
              value: 'false'
            - name: PGRST_JWT_SECRET
              value: {{ .Values.envMap.JWT_SECRET | quote }}
          image: {{ .Values.images.rest }}
          name: supabase-rest
