apiVersion: v1
kind: Service
metadata:
  labels:
    app: supavisor
  name: supavisor
spec:
  ports:
    - name: '5432'
      port: 5432
      targetPort: 5432
    - name: '6543'
      port: 6543
      targetPort: 6543
  selector:
    app: supavisor
