apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vector
  name: vector
spec:
  replicas: 0
  selector:
    matchLabels:
      app: vector
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vector
    spec:
      restartPolicy: Always
      containers:
        - args:
            - --config
            - /etc/vector/vector.yml
          env:
            - name: LOGFLARE_PUBLIC_ACCESS_TOKEN
              value: {{ .Values.envMap.LOGFLARE_PUBLIC_ACCESS_TOKEN.value | quote }}
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: {{ .Values.images.vector }}
          # livenessProbe:
          #   exec:
          #     command:
          #       - wget
          #       - --no-verbose
          #       - --tries=1
          #       - --spider
          #       - http://vector.{{ .Values.identifier }}:9001/health
          #   failureThreshold: 3
          #   periodSeconds: 5
          #   timeoutSeconds: 5
          name: supabase-vector
          ports:
            - containerPort: 9001
          volumeMounts:
            - mountPath: /etc/vector/vector.yml
              subPath: vector.yml
              name: vector-config
              readOnly: true
      volumes:
        - name: vector-config
          configMap:
            name: vector-config
